# Generated by Django 2.0.4 on 2018-04-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180421_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=800, verbose_name='Описание'),
        ),
    ]
